import { describe, expect, it } from "vitest";
import { calculateShiftSummaries } from "@/utils/hitunganHarianCalculations";
import type { PemasukanData } from "@/types/PemasukanData";

describe("hitunganHarianCalculations", () => {
  it("splits apotek debit into mandiri and qris correctly", () => {
    const mockData: PemasukanData[] = [
      {
        _id: "tx1",
        status: "paid off",
        totalFee: 50000,
        creditFee: 0,
        isOnlyPOS: true,
        createdAt: "2025-09-17T09:00:00+07:00", // Pagi shift
        code: "INV001",
        debtFee: 0,
        isOutcome: false,
        paidFee: 50000,
        sumFee: 0,
        roundedValue: 0,
        Appointment: {},
        Diagnoses: [],
        OtherNotes: [],
        Practices: {},
        Items: [
          {
            _id: "item1",
            name: "Paracetamol",
            type: "prescription",
            hospitalId: "h1",
            transactionId: "tx1",
            quantity: 1,
            baseFee: 50000,
            discount: 0,
            totalFee: 50000,
            isPriceLock: true,
            paidFee: 50000,
            payableFee: 0,
            transactionType: "selling",
            categoryId: "c1",
            isPaidOff: true,
            createdAt: "2025-09-17T08:00:00.000Z",
            updatedAt: "2025-09-17T08:00:00.000Z",
            createdId: "u1",
            medicalHelperIds: [],
            createdName: "Cashier",
            incomeType: "apotek",
            isPendingStock: false,
            isSlotTransacted: true,
          },
        ],
        Payments: [
          {
            _id: "p1",
            totalFee: 50000,
            percentageTotal: 100,
            status: "paid",
            type: "Kartu Debit",
            name: "QRIS",
            transactionId: "tx1",
            transactionDate: "2025-09-17T08:00:00.000Z",
            accountTxId: "acc1",
            hospitalId: "h1",
            reason: "Konsultasi",
            isCovered: false,
            isNeedClaim: false,
            isOutcome: false,
            intent: "-",
            createdAt: "2025-09-17T08:00:00.000Z",
            createdId: "u1",
            paidName: "-",
            change: 0,
            createdName: "Cashier",
            trueCreatedAt: "2025-09-17T08:00:00.000Z",
          },
        ],
      },
      {
        _id: "tx2",
        status: "paid off",
        totalFee: 75000,
        creditFee: 0,
        isOnlyPOS: true,
        createdAt: "2025-09-17T10:00:00+07:00", // Pagi shift
        code: "INV002",
        debtFee: 0,
        isOutcome: false,
        paidFee: 75000,
        sumFee: 0,
        roundedValue: 0,
        Appointment: {},
        Diagnoses: [],
        OtherNotes: [],
        Practices: {},
        Items: [
          {
            _id: "item2",
            name: "Amoxicillin",
            type: "prescription",
            hospitalId: "h1",
            transactionId: "tx2",
            quantity: 1,
            baseFee: 75000,
            discount: 0,
            totalFee: 75000,
            isPriceLock: true,
            paidFee: 75000,
            payableFee: 0,
            transactionType: "selling",
            categoryId: "c1",
            isPaidOff: true,
            createdAt: "2025-09-17T10:00:00+07:00",
            updatedAt: "2025-09-17T10:00:00+07:00",
            createdId: "u1",
            medicalHelperIds: [],
            createdName: "Cashier",
            incomeType: "apotek",
            isPendingStock: false,
            isSlotTransacted: true,
          },
        ],
        Payments: [
          {
            _id: "p2",
            totalFee: 75000,
            percentageTotal: 100,
            status: "paid",
            type: "Kartu Debit",
            name: "Bank Mandiri",
            transactionId: "tx2",
            transactionDate: "2025-09-17T10:00:00+07:00",
            accountTxId: "acc1",
            hospitalId: "h1",
            reason: "Konsultasi",
            isCovered: false,
            isNeedClaim: false,
            isOutcome: false,
            intent: "-",
            createdAt: "2025-09-17T10:00:00+07:00",
            createdId: "u1",
            paidName: "-",
            change: 0,
            createdName: "Cashier",
            trueCreatedAt: "2025-09-17T10:00:00+07:00",
          },
        ],
      },
      {
        _id: "tx3",
        status: "paid off",
        totalFee: 20000,
        creditFee: 0,
        isOnlyPOS: true,
        createdAt: "2025-09-17T11:00:00+07:00", // Pagi shift
        code: "INV003",
        debtFee: 0,
        isOutcome: false,
        paidFee: 20000,
        sumFee: 0,
        roundedValue: 0,
        Appointment: {},
        Diagnoses: [],
        OtherNotes: [],
        Practices: {},
        Items: [
          {
            _id: "item3",
            name: "Sanmol",
            type: "prescription",
            hospitalId: "h1",
            transactionId: "tx3",
            quantity: 1,
            baseFee: 20000,
            discount: 0,
            totalFee: 20000,
            isPriceLock: true,
            paidFee: 20000,
            payableFee: 0,
            transactionType: "selling",
            categoryId: "c1",
            isPaidOff: true,
            createdAt: "2025-09-17T11:00:00+07:00",
            updatedAt: "2025-09-17T11:00:00+07:00",
            createdId: "u1",
            medicalHelperIds: [],
            createdName: "Cashier",
            incomeType: "apotek",
            isPendingStock: false,
            isSlotTransacted: true,
          },
        ],
        Payments: [
          {
            _id: "p3",
            totalFee: 20000,
            percentageTotal: 100,
            status: "paid",
            type: "Langsung",
            name: "Tunai",
            transactionId: "tx3",
            transactionDate: "2025-09-17T11:00:00+07:00",
            accountTxId: "acc1",
            hospitalId: "h1",
            reason: "-",
            isCovered: false,
            isNeedClaim: false,
            isOutcome: false,
            intent: "-",
            createdAt: "2025-09-17T11:00:00+07:00",
            createdId: "u1",
            paidName: "-",
            change: 0,
            createdName: "Cashier",
            trueCreatedAt: "2025-09-17T11:00:00+07:00",
          },
        ],
      },
    ];

    const summaries = calculateShiftSummaries(mockData);
    expect(summaries).toHaveLength(1);
    const summary = summaries[0];
    expect(summary.shift).toBe("Pagi");
    expect(summary.apotek.cash).toBe(20000);
    expect(summary.apotek.mandiri).toBe(75000);
    expect(summary.apotek.qris).toBe(50000);
    expect(summary.apotek.total).toBe(145000);
  });
});
